triggers:
   - name: fl-tg1
     type: trigger
     version:
       counter: 1
       
   - name: fl-tg2
     type: trigger
     version:
       counter: 1
       
   - name: fl-tg3
     type: trigger
     version:
       counter: 1
       
   - name: fl-tg4
     type: trigger
     version:
       counter: 1
       
   - name: fl-tg5
     type: trigger
     version:
       counter: 2
       
   - name: fl-tg6
     type: trigger
     version:
       counter: 1
       
   - name: fl-tg7
     type: trigger
     version:
       counter: 1
       
   - name: fl-tg8
     type: trigger
     version:
       counter: 1
