triggers:
   - name: bb-tg1
     type: trigger
     version:
       counter: 2
       
   - name: bb-tg2
     type: trigger
     version:
       counter: 1
       
   - name: bb-tg5
     type: trigger
     version:
       counter: 1
