jobs:
      
  - name: fl-man1
    type: manifest
    steps:
      - IN: fl-img1
      - IN: fl-tg1
      
        
  - name: fl-ddcdeploy
    type: deploy
    steps:
      - IN: fl-man1
      - IN: fl-ddccluster
