jobs:

#RELEASE

  - name: bb-release
    type: release
    steps:
      - IN: bb-version
      - TASK: managed
        bump: beta
      - IN: bb-man1
      #- IN: bb-tg1
      
#MANIFESTS
      
  - name: bb-man1
    type: manifest
    steps:
      - IN: bb-img1
      - IN: bb-tg1

# DEPLOYMENTS 

  - name: bb-ddcdeployup
    type: deploy
    steps:
      - IN: bb-man1
      - IN: bb-ddccluster
