jobs:
      
  - name: bb-man1
    type: manifest
    steps:
      - IN: bb-img1
      - IN: bb-tg1
      
        
  - name: bb-ddcdeploy
    type: deploy
    steps:
      - IN: bb-man1
      - IN: bb-ddccluster
