jobs:
      
  - name: fl-man1
    type: manifest
    steps:
      - IN: fl-img1
      - IN: fl-tg1
      
  - name: fl-man5driftking
    type: manifest
    steps:
      - IN: fl-img5workingdir
      - IN: fl-tg5
      - TASK: managed

  - name: fl-ecsdeployup
    type: deploy
    steps:
      - IN: fl-man1
      - IN: fl-ecscluster
      - TASK: managed
        deployMethod: upgrade
        
  - name: fl-gkedeploybg
    type: deploy
    steps:
      - IN: fl-man5driftking
      - IN: flgke-dopts3
      - IN: fl-gkecluster
