jobs:
      
#MANIFEST

  - name: bb-man1
    type: manifest
    steps:
      - IN: bb-img1
      - IN: bb-time
      - IN: bb-tg1
    on_start:
      - NOTIFY: bb-email
      - NOTIFY: bb-slack
    on_success:
      - NOTIFY: bb-email
      - NOTIFY: bb-slack
      
#DEPLOY    

 # - name: bb-ddcdeploy
  #  type: deploy
   # steps:
    #  - IN: bb-man1
     # - IN: bb-ddccluster      

#RELEASE

  - name: bb-release1
    type: release
    steps:
      - IN: bb-version
      - TASK: managed
        bump: beta
    #  - IN: bb-man1
  #    - IN: bb-tg1
      
  #- name: bb-rsync1
   # type: rSync
    #steps:
     # - IN: bbsyncRepo_samplefleming_syncgitrepo
      #- IN: bb-tg1
